[package]
name = "solana_transactions"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-client = "1.18.14"
solana-sdk = "1.18.14"
solana-program = "1.18.26"
anyhow = "1.0"
tokio = { version = "1.38", features = ["full"] }

